create database sp;
use sp;

select * from healthcare;

/*Write SQL queries to retrieve and
manipulate data for below questions :*/

-- 1. Retrieve the names of all patients in the database.
select name from healthcare;

-- 2. List the unique medical conditions present in the dataset.
SELECT medical_condition
FROM healthcare
GROUP BY medical_condition;

select distinct medical_condition from healthcare;

-- 3. Find the total number of doctors in the healthcare system.
select count(doctor) from healthcare;

-- 4. Retrieve the details of all female patients.
select 	* from healthcare where gender='female';

-- 5. what is the average age of patients in the database.
select avg(age) from healthcare;

-- 6. Identify the patients who have more than one medical condition.
select name , count(medical_condition) from healthcare group by name having count(medical_condition)>1;

-- 7. List the names of all doctors.
select doctor from healthcare; 

-- 8.Identify the most common medical condition among patients.
select medical_condition,count(medical_condition) from healthcare
group by medical_condition order by  count(Medical_Condition) desc limit 1;

-- 9.Find the patients who are older than 60 years and have diabetes.
select name from healthcare 
where age >60 and medical_condition ='diabetes';

-- 10.Calculate the total revenue generated by the healthcare system. 
select sum(Billing_Amount) from Healthcare;

-- 11.Find the doctor with the oldest patient.
select doctor,name,age from healthcare  order by age  desc limit 1;

-- 12.Calculate the average duration of medical visits.
select avg(duration) from healthcare;

-- 13.Give the names of patients whose name starts with A.
select name from healthcare where name like 'a%';


-- 14.How many male and female patients are there in dataset.
select gender,count(gender) from healthcare group by gender;

-- 15.how many patients are normal.
select test_results, count(test_results) from healthcare  where Test_Results='Normal';

-- 16.how many patients are abnormal or Inconclusive.
select test_results, count(test_results) from healthcare  group by test_results;

-- 17.how many patients of blood group AB+ are there of age above 52.
select blood_type,count(*) from healthcare where blood_type='AB+'  and age >52;

-- 18. how many patients have paid the bill above 24890.
select  count(*)
from Healthcare
where Billing_Amount>24890;

-- 19. what are the names of patients having Asthma.
select name from healthcare where Medical_Condition ='Asthma';

-- 20. how many patients have cancer.
select count(*) from healthcare where Medical_Condition ='cancer';

-- 21. what are the names and blood groups of patients admitted to room no. 292.
select Name ,Blood_Type from Healthcare
where Room_Number=292;

-- 22. how many males have Arthritis.
select Medical_Condition,count(Medical_Condition) from Healthcare
where Medical_Condition='Arthritis';

-- 23. How many patients were admitted to Harris and Sons hospital.
select Hospital,count(Hospital)
 from Healthcare
where Hospital='Harris and Sons';

-- 24. what are the names of patients whose Insurance Provider are Cigna.
select Name from Healthcare
where Insurance_Provider='Cigna';

-- 25. Name the Medical Condition having patients whose ages is greater than average age
select medical_condition,age from healthcare where age > (select avg(age) from healthcare) ;
